name: CMake Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake (Library)
      run: cmake -B ${{github.workspace}}/logger_lib/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}}/logger_lib
      
    - name: Build Library
      run: cmake --build ${{github.workspace}}/logger_lib/build --config ${{env.BUILD_TYPE}}
      
    - name: Install Library (Test Installation)
      run: cmake --install ${{github.workspace}}/logger_lib/build --prefix ${{github.workspace}}/install
      
    - name: Verify Installation
      run: |
        echo "Checking installed files:"
        find ${{github.workspace}}/install -type f | sort
        echo "Library build completed successfully!"
